name: Typescript CI

on:
  pull_request:
    paths:
      - "app_typescript/**"
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: cd ./app_typescript && npm ci

      - name: Linter
        run: cd ./app_typescript && npm run lint

      - name: Build Next.js app
        run: cd ./app_typescript && npm run build

      # - name: Run tests
      #   run: npm run test

      # - name: Publish artifacts
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: nextjs-app
      #     path: .next

  snyk:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --file=app_typescript/package-lock.json
            --package-manager=npm
            --skip-unresolved

  docker:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache Docker layers
        id: cache
        uses: actions/cache@v3
        with:
          path: |
            /var/lib/docker
            ~/.cache/docker
          key: ${{ runner.os }}-${{ hashFiles('**/Dockerfile') }}-docker-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-${{ hashFiles('**/Dockerfile') }}-docker-

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./app_python/
          file: app_python/Dockerfile
          push: true
          tags: bellissimo/devops-inno-daniil-okrug:latest-typescript
